import React, { useEffect, useState } from "react";
import { officerRequest } from "./api";

export default function OfficerConsole() {
  const [centreId, setCentreId] = useState(1); const [queue, setQueue] = useState([]); const [result, setResult] = useState(null);
  const [form, setForm] = useState({ centre_id: 1, for_date: new Date().toISOString().slice(0, 10), counters: 2, rate_per_counter: 25, hours: 8, bags_available: 3000, qtl_per_bag: .4, hamalis: 6, rate_per_hamali: 90, buffer_capacity: 2500, stock_open: 1800, trucks: 2, trips_per_truck: 1, qtl_per_truck: 250 });
  useEffect(() => { officerRequest(`/officer/queue?centre_id=${centreId}`).then(setQueue); }, [centreId]);
  const advance = async lot => { const action = { REGISTERED: "arrive", ARRIVED: "weigh", WEIGHED: "grade", GRADED: "lift", LIFTED: "settle" }[lot.state]; if (!action) return; const payload = { centre_id: Number(centreId) }; if (action === "arrive") payload.token_no = Number(prompt("Token number")); if (action === "weigh") payload.gross_qtl = Number(prompt("Gross quintals")); if (action === "grade") { payload.grade = prompt("Grade"); payload.moisture_pct = Number(prompt("Moisture %")); payload.net_qtl = Number(prompt("Net quintals")); payload.amount_due = Number(prompt("Amount due")); } if (action === "lift") { payload.truck_no = prompt("Truck number"); payload.mill = prompt("Mill"); } if (action === "settle") { payload.reference = prompt("Payment reference"); payload.amount = Number(prompt("Amount")); } await officerRequest(`/officer/lots/${lot.id}/${action}`, { method: "POST", body: JSON.stringify(payload) }); setQueue(await officerRequest(`/officer/queue?centre_id=${centreId}`)); };
  const submit = async event => { event.preventDefault(); setResult(await officerRequest("/officer/capacity", { method: "POST", body: JSON.stringify(form) })); };
  return <section className="officer-screen"><h1>Centre officer console</h1><form onSubmit={submit}>{Object.entries(form).map(([key, value]) => <label key={key}>{key.replaceAll("_", " ")}<input type={key === "for_date" ? "date" : "number"} step="any" value={value} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>)}<button>Calculate capacity</button></form>{result && <div className="constraints">{[["STAFF", result.staff_cap], ["BAGS", result.bag_cap], ["HAMALI", result.hamali_cap], ["YARD", result.yard_cap]].map(([name, value]) => <div className={name === result.binding_constraint ? "constraint binding" : "constraint"} key={name}>{name}: {value} qtl</div>)}<div>Lift: {result.lift_today} · Daily: {result.daily_capacity} · Bookable: {result.bookable_qtl} · Choked: {String(result.choked)}</div></div>}<h2>Today’s queue</h2><table><thead><tr><th>Token</th><th>Lot</th><th>State</th><th>Action</th></tr></thead><tbody>{queue.map(lot => <tr key={lot.id}><td>{lot.token_no}</td><td>{lot.id}</td><td>{lot.state}</td><td>{{ REGISTERED: "Arrive", ARRIVED: "Weigh", WEIGHED: "Grade", GRADED: "Lift", LIFTED: "Settle" }[lot.state] && <button onClick={() => advance(lot)}>{{ REGISTERED: "Arrive", ARRIVED: "Weigh", WEIGHED: "Grade", GRADED: "Lift", LIFTED: "Settle" }[lot.state]}</button>}</td></tr>)}</tbody></table></section>;
}
